============================= test session starts ==============================
platform linux -- Python 3.8.2, pytest-5.4.2, py-1.8.1, pluggy-0.13.1 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/vicferpoy/Desktop/Git/wazuh/api/test/integration, inifile: pytest.ini
plugins: tavern-1.0.0
collecting ... collected 0 items / 1 error

==================================== ERRORS ====================================
______________ ERROR collecting test_rules_endpoints.tavern.yaml _______________
/home/vicferpoy/.local/lib/python3.8/site-packages/tavern/testutils/pytesthook/file.py:271: in collect
    all_tests = list(
/usr/lib/python3/dist-packages/yaml/__init__.py:130: in load_all
    yield loader.get_data()
/usr/lib/python3/dist-packages/yaml/constructor.py:45: in get_data
    return self.construct_document(self.get_node())
/usr/lib/python3/dist-packages/yaml/composer.py:27: in get_node
    return self.compose_document()
/home/vicferpoy/.local/lib/python3.8/site-packages/tavern/util/loader.py:38: in compose_document
    node = self.compose_node(None, None)
/usr/lib/python3/dist-packages/yaml/composer.py:84: in compose_node
    node = self.compose_mapping_node(anchor)
/usr/lib/python3/dist-packages/yaml/composer.py:133: in compose_mapping_node
    item_value = self.compose_node(node, item_key)
/usr/lib/python3/dist-packages/yaml/composer.py:82: in compose_node
    node = self.compose_sequence_node(anchor)
/usr/lib/python3/dist-packages/yaml/composer.py:111: in compose_sequence_node
    node.value.append(self.compose_node(node, index))
/usr/lib/python3/dist-packages/yaml/composer.py:84: in compose_node
    node = self.compose_mapping_node(anchor)
/usr/lib/python3/dist-packages/yaml/composer.py:133: in compose_mapping_node
    item_value = self.compose_node(node, item_key)
/usr/lib/python3/dist-packages/yaml/composer.py:84: in compose_node
    node = self.compose_mapping_node(anchor)
/usr/lib/python3/dist-packages/yaml/composer.py:133: in compose_mapping_node
    item_value = self.compose_node(node, item_key)
/usr/lib/python3/dist-packages/yaml/composer.py:84: in compose_node
    node = self.compose_mapping_node(anchor)
/usr/lib/python3/dist-packages/yaml/composer.py:133: in compose_mapping_node
    item_value = self.compose_node(node, item_key)
/usr/lib/python3/dist-packages/yaml/composer.py:68: in compose_node
    raise ComposerError(None, None, "found undefined alias %r"
E   yaml.composer.ComposerError: found undefined alias 'error_response'
E     in "/home/vicferpoy/Desktop/Git/wazuh/api/test/integration/test_rules_endpoints.tavern.yaml", line 225, column 13
=============================== warnings summary ===============================
/home/vicferpoy/.local/lib/python3.8/site-packages/tavern/testutils/pytesthook/hooks.py:83
  /home/vicferpoy/.local/lib/python3.8/site-packages/tavern/testutils/pytesthook/hooks.py:83: PytestDeprecationWarning: direct construction of YamlFile has been deprecated, please use YamlFile.from_parent
    return YamlFile(path, parent)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
=========================== short test summary info ============================
ERROR test_rules_endpoints.tavern.yaml - yaml.composer.ComposerError: found u...
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
========================= 1 warning, 1 error in 0.10s ==========================
